In [4]:
! pip install yfinance

Requirement already satisfied: yfinance in c:\users\afraa\anaconda3\lib\site-packages (0.2.33)
Requirement already satisfied: pandas>=1.3.0 in c:\users\afraa\anaconda3\lib\site-packages (from yfinance) (2.0.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\afraa\anaconda3\lib\site-packages (from yfinance) (1.24.3)
Requirement already satisfied: requests>=2.31 in c:\users\afraa\anaconda3\lib\site-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\afraa\anaconda3\lib\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in c:\users\afraa\anaconda3\lib\site-packages (from yfinance) (4.9.3)
Requirement already satisfied: appdirs>=1.4.4 in c:\users\afraa\anaconda3\lib\site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in c:\users\afraa\anaconda3\lib\site-packages (from yfinance) (2023.3.post1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\afraa\anaconda3\lib\site-packages (from yfinance) (2.4.0)
Requirement already satisfied: peewee>=3.16.2 in c:\users\afraa\anaconda3\lib\site-packages (from yfinance) (3.17.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\afraa\anaconda3\lib\site-packages (from yfinance) (4.12.2)
Requirement already satisfied: html5lib>=1.1 in c:\users\afraa\anaconda3\lib\site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\afraa\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4)
Requirement already satisfied: six>=1.9 in c:\users\afraa\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\users\afraa\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\afraa\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\afraa\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\afraa\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\afraa\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\afraa\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\afraa\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2023.11.17)

In [7]:
import yfinance as yf

#Define ticker symbol

ticker_symbol = "AAPL"

# Create a ticker object

ticker = yf.Ticker(ticker_symbol)

# Download Historical Data
historical_data = ticker.history(start = "1990-01-01", end="2022-12-21", interval='1d')
historical_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1990-01-02 00:00:00-05:00,0.249271,0.265181,0.247503,0.263414,183198400,0.0,0.0
1990-01-03 00:00:00-05:00,0.268718,0.268718,0.265181,0.265181,207995200,0.0,0.0
1990-01-04 00:00:00-05:00,0.270486,0.274021,0.263414,0.266066,221513600,0.0,0.0
1990-01-05 00:00:00-05:00,0.266950,0.270486,0.261646,0.266950,123312000,0.0,0.0
1990-01-08 00:00:00-05:00,0.265181,0.268718,0.261646,0.268718,101572800,0.0,0.0
...,...,...,...,...,...,...,...
2022-12-14 00:00:00-05:00,144.542091,145.844807,140.375378,142.413986,82291200,0.0,0.0
2022-12-15 00:00:00-05:00,140.325632,141.011799,135.273868,135.741257,98931900,0.0,0.0
2022-12-16 00:00:00-05:00,135.930220,136.884875,132.986666,133.762329,160156900,0.0,0.0
2022-12-19 00:00:00-05:00,134.358991,134.448488,130.590065,131.634216,79592600,0.0,0.0
2022-12-20 00:00:00-05:00,130.659676,132.509337,129.168013,131.564621,77432800,0.0,0.0

In [9]:
# inCase if you want to download the last days or shorter period use the following method:

history_data = ticker.history(period = "20d", interval = "1d")
history_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-12-01 00:00:00-05:00,190.330002,191.559998,189.229996,191.240005,45679300,0.0,0.0
2023-12-04 00:00:00-05:00,189.979996,190.050003,187.449997,189.429993,43389500,0.0,0.0
2023-12-05 00:00:00-05:00,190.210007,194.399994,190.179993,193.419998,66628400,0.0,0.0
2023-12-06 00:00:00-05:00,194.449997,194.759995,192.110001,192.320007,41089700,0.0,0.0
2023-12-07 00:00:00-05:00,193.630005,195.000000,193.589996,194.270004,47477700,0.0,0.0
2023-12-08 00:00:00-05:00,194.199997,195.990005,193.669998,195.710007,53377300,0.0,0.0
2023-12-11 00:00:00-05:00,193.110001,193.490005,191.419998,193.179993,60943700,0.0,0.0
2023-12-12 00:00:00-05:00,193.080002,194.720001,191.720001,194.710007,52696900,0.0,0.0
2023-12-13 00:00:00-05:00,195.089996,198.000000,194.850006,197.960007,70404200,0.0,0.0
2023-12-14 00:00:00-05:00,198.020004,199.619995,196.160004,198.110001,66831600,0.0,0.0
2023-12-15 00:00:00-05:00,197.529999,198.399994,197.000000,197.570007,128256700,0.0,0.0
2023-12-18 00:00:00-05:00,196.089996,196.630005,194.389999,195.889999,55751900,0.0,0.0
2023-12-19 00:00:00-05:00,196.160004,196.949997,195.889999,196.940002,40714100,0.0,0.0
2023-12-20 00:00:00-05:00,196.899994,197.679993,194.830002,194.830002,52242800,0.0,0.0
2023-12-21 00:00:00-05:00,196.100006,197.080002,193.500000,194.679993,46482500,0.0,0.0
2023-12-22 00:00:00-05:00,195.179993,195.410004,192.970001,193.600006,37122800,0.0,0.0
2023-12-26 00:00:00-05:00,193.610001,193.889999,192.830002,193.050003,28919300,0.0,0.0
2023-12-27 00:00:00-05:00,192.490005,193.500000,191.089996,193.149994,48087700,0.0,0.0
2023-12-28 00:00:00-05:00,194.139999,194.660004,193.169998,193.580002,34049900,0.0,0.0
2023-12-29 00:00:00-05:00,193.899994,194.399994,191.729996,192.529999,42628800,0.0,0.0